name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
          check-latest: true

      - name: Get Dependencies
        run: |
          go mod download

      - name: Build
        run: go build .

      - name: Test With Coverage
        run: go test -v  -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
